<a href="https://colab.research.google.com/github/oneonethree113/Advanced-Python-Learning/blob/main/LSTM_learn_addition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [283]:
import torch
import torch.nn as nn
import random

# Define the LSTM model
class LSTMAdditionModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(LSTMAdditionModel, self).__init__()
        self.hidden_size = hidden_size
        self.lstm = nn.LSTM(input_size, hidden_size, batch_first=True)
        self.linear = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        lstm_out, _ = self.lstm(x)
        output = self.linear(lstm_out)
        return output


In [485]:
import torch

def generate_output_data(input_data):
    output_data = []

    for sample in input_data:
      cumulative_sum = 0.0
      sample_output_data=[]
      for value in sample:

        cumulative_sum += value[0]
        sample_output_data.append([cumulative_sum])
      output_data.append(sample_output_data)

    return torch.tensor(output_data)

random.seed(42)
# Create sample input data
input_data =([[[3], [0.1], [0.3]],
                           [[0.2], [0.3], [0.4]],
                           [[0.3], [0.4], [0.5]],
                           [[1.3], [0.4], [0.5]]])
input_data= [ ([[random.uniform(-10, 10)] for _ in range(3)] )  for _ in range(1000) ]
# Generate output data
output_data = generate_output_data(input_data)
print("Generated Input Data:")
print(input_data[0])
print("Generated Output Data:")
print(output_data[0])
input_data=torch.tensor(input_data)

Generated Input Data:
[[2.7885359691576745], [-9.49978489554666], [-4.499413632617615]]
Generated Output Data:
tensor([[  2.7885],
        [ -6.7112],
        [-11.2107]])


In [488]:
import torch
torch.manual_seed(1)
# Define hyperparameters
input_size = 1
hidden_size = 1
output_size = 1
batch_size = 3  # Number of samples in each batch
num_epochs = 10000
learning_rate = 0.01

# Initialize the model
AdditionModel = LSTMAdditionModel(input_size, hidden_size, output_size)

# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(AdditionModel.parameters(), lr=learning_rate)

# Training loop
for epoch in range(num_epochs):
    optimizer.zero_grad()
    outputs = AdditionModel(input_data)
    loss = criterion(outputs, output_data)
    loss.backward()
    optimizer.step()

    if (epoch+1) % 500 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [500/10000], Loss: 20.8938
Epoch [1000/10000], Loss: 8.5162
Epoch [1500/10000], Loss: 4.7065
Epoch [2000/10000], Loss: 3.0729
Epoch [2500/10000], Loss: 2.1939
Epoch [3000/10000], Loss: 1.6498
Epoch [3500/10000], Loss: 1.2819
Epoch [4000/10000], Loss: 1.0183
Epoch [4500/10000], Loss: 0.8218
Epoch [5000/10000], Loss: 0.6710
Epoch [5500/10000], Loss: 0.5526
Epoch [6000/10000], Loss: 0.4583
Epoch [6500/10000], Loss: 0.3823
Epoch [7000/10000], Loss: 0.3204
Epoch [7500/10000], Loss: 0.2696
Epoch [8000/10000], Loss: 0.3610
Epoch [8500/10000], Loss: 0.2575
Epoch [9000/10000], Loss: 0.1649
Epoch [9500/10000], Loss: 0.2501
Epoch [10000/10000], Loss: 0.1239


Good, It can do a list of addition

In [489]:
test_data=[0.2,0.1,0.7,0.1]
test_data=[[[i] for i in test_data]]
testPredict_data = generate_output_data(test_data)
print("Generated Input Data:")
print(test_data)
print("Generated Output Data:")
print(testPredict_data)
AdditionModel(torch.tensor(test_data))

Generated Input Data:
[[[0.2], [0.1], [0.7], [0.1]]]
Generated Output Data:
tensor([[[0.2000],
         [0.3000],
         [1.0000],
         [1.1000]]])


tensor([[[0.2192],
         [0.2990],
         [1.0185],
         [1.1104]]], grad_fn=<ViewBackward0>)

Why can't LSTM do looping?!

In [506]:
import torch
import torch.nn as nn

# Define the LSTM model
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size,max_length):
        super(LSTMModel, self).__init__()
        self.hidden_size = hidden_size
        self.lstm = nn.LSTM(input_size, hidden_size,2, batch_first=True)
        self.linear = nn.Linear(hidden_size, output_size)
        self.max_length = max_length

    def forward(self, input_tuple):
        lstm_input = input_tuple.unsqueeze(0).repeat(max_length, 1, 1)
        #print(lstm_input)
        lstm_out, _ = self.lstm(lstm_input)
        output = self.linear(lstm_out)
        return output
def generate_output_data_multtoadd(input_data,length):
    output_data = []

    for sample in input_data:
      #sample_output_data=[sample[1] if i<sample[0] else 0.0 for i in range(length)]
      sample_output_data=[[sample[1] ] if i<sample[0] else [0] for i in range(length)]
      output_data.append(sample_output_data)
      print(sample, sample_output_data)
    return torch.tensor(output_data)
# Define hyperparameters
input_size = 2
hidden_size = 20
output_size = 1
max_length = 1
# Create sample input data
input_data = [(2.0, 2.0),(3.0, 1.0),(1.0, 3.0)]
input_data=[(float(random.randint(0, max_length)),float(random.randint(1, 10))) for _ in range(20 )]
# Initialize the model
model = LSTMModel(input_size, hidden_size, output_size,max_length)

# Test the model
for input_tuple in input_data:
    input_tuple = (torch.tensor([input_tuple[0],input_tuple[1]]))
    with torch.no_grad():
        predicted_output = model(input_tuple)

output_data=generate_output_data_multtoadd(input_data,max_length)


(0.0, 3.0) [[0]]
(1.0, 6.0) [[6.0]]
(0.0, 2.0) [[0]]
(1.0, 9.0) [[9.0]]
(1.0, 9.0) [[9.0]]
(1.0, 5.0) [[5.0]]
(1.0, 1.0) [[1.0]]
(1.0, 2.0) [[2.0]]
(1.0, 3.0) [[3.0]]
(0.0, 10.0) [[0]]
(0.0, 2.0) [[0]]
(0.0, 5.0) [[0]]
(1.0, 7.0) [[7.0]]
(1.0, 7.0) [[7.0]]
(1.0, 10.0) [[10.0]]
(1.0, 1.0) [[1.0]]
(0.0, 5.0) [[0]]
(1.0, 3.0) [[3.0]]
(1.0, 1.0) [[1.0]]
(1.0, 6.0) [[6.0]]


In [509]:
num_epochs=300
learning_rate=0.001
# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(num_epochs):
    total_loss = 0
    for i, input_tuple in enumerate(input_data):
        input_tuple = (torch.tensor([input_tuple[0],input_tuple[1]]))
        target = torch.tensor(output_data[i])

        optimizer.zero_grad()
        outputs = model(input_tuple)
        loss = criterion(outputs, target)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {total_loss:.4f}')
input_tuple=input_data[0]
print(input_tuple)
print("Predicted Output:")
print(model((torch.tensor([input_tuple[0],input_tuple[1]]))))
print("True Output:")
print(output_data[0])

<ipython-input-509-1e2763ae49fc>:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  target = torch.tensor(output_data[i])


Epoch [100/300], Loss: 0.0093
Epoch [200/300], Loss: 0.0033
Epoch [300/300], Loss: 0.0031
(0.0, 3.0)
Predicted Output:
tensor([[[0.0270]]], grad_fn=<ViewBackward0>)
True Output:
tensor([[0.]])


In [510]:

# Define hyperparameters
input_size = 2
hidden_size = 20
output_size = 1
max_length = 2
# Create sample input data
input_data = [(2.0, 2.0),(3.0, 1.0),(1.0, 3.0)]
input_data=[(float(random.randint(0, max_length)),float(random.randint(1, 10))) for _ in range(20 )]

# Test the model
for input_tuple in input_data:
    input_tuple = (torch.tensor([input_tuple[0],input_tuple[1]]))
    with torch.no_grad():
        predicted_output = model(input_tuple)

output_data=generate_output_data_multtoadd(input_data,max_length)

(2.0, 4.0) [[4.0], [4.0]]
(0.0, 8.0) [[0], [0]]
(1.0, 6.0) [[6.0], [0]]
(0.0, 6.0) [[0], [0]]
(1.0, 5.0) [[5.0], [0]]
(1.0, 8.0) [[8.0], [0]]
(2.0, 2.0) [[2.0], [2.0]]
(0.0, 3.0) [[0], [0]]
(1.0, 8.0) [[8.0], [0]]
(1.0, 5.0) [[5.0], [0]]
(2.0, 7.0) [[7.0], [7.0]]
(2.0, 2.0) [[2.0], [2.0]]
(0.0, 8.0) [[0], [0]]
(0.0, 7.0) [[0], [0]]
(2.0, 8.0) [[8.0], [8.0]]
(2.0, 6.0) [[6.0], [6.0]]
(0.0, 9.0) [[0], [0]]
(0.0, 2.0) [[0], [0]]
(1.0, 9.0) [[9.0], [0]]
(1.0, 3.0) [[3.0], [0]]


In [512]:
num_epochs=1000
learning_rate=0.0001
# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(num_epochs):
    total_loss = 0
    for i, input_tuple in enumerate(input_data):
        input_tuple = (torch.tensor([input_tuple[0],input_tuple[1]]))
        target = torch.tensor(output_data[i])

        optimizer.zero_grad()
        outputs = model(input_tuple)
        loss = criterion(outputs, target)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {total_loss:.4f}')
input_tuple=input_data[0]
print(input_tuple)
print("Predicted Output:")
print(model((torch.tensor([input_tuple[0],input_tuple[1]]))))
print("True Output:")
print(output_data[0])

<ipython-input-512-6b7c2fa7988a>:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  target = torch.tensor(output_data[i])


Epoch [100/300], Loss: 76.0786
Epoch [200/300], Loss: 76.0393
Epoch [300/300], Loss: 76.0237
(2.0, 4.0)
Predicted Output:
tensor([[[3.9220]],

        [[3.9220]]], grad_fn=<ViewBackward0>)
True Output:
tensor([[4.],
        [4.]])


In [505]:
i=4

input_tuple=input_data[i]
print(input_tuple)
print("Predicted Output:")
print(model((torch.tensor([input_tuple[0],input_tuple[1]]))))
print("True Output:")
print(output_data[i])

(1.0, 9.0)
Predicted Output:
tensor([[[4.4510]],

        [[4.4510]]], grad_fn=<ViewBackward0>)
True Output:
tensor([[9.],
        [0.]])


In [434]:
input_tuple=(20.0,20.0)
print(input_tuple)
print("Predicted Output:")
print(model((torch.tensor([input_tuple[0],input_tuple[1]]))))
print("True Output:")
print(input_tuple[1]*input_tuple[0])

(20.0, 20.0)
Predicted Output:
tensor([[[3.7709]],

        [[3.7709]],

        [[3.7709]]], grad_fn=<ViewBackward0>)
True Output:
400.0
